name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

    - name: Set repo to lowercase
      id: repo
      run: echo "::set-output name=repo::$(echo ${{ github.repository }} | awk '{print tolower($0)}')"

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ steps.repo.outputs.repo }}:${{ steps.date.outputs.date }}

    - name: Test if the image serves the page
      run: |
        docker run -p -d 80:80 ghcr.io/${{ steps.repo.outputs.repo }}:${{ steps.date.outputs.date }}
        curl --max-time 10 --retry 5 http://localhost:80