name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Save state
      run: |
        echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

    - name: Set repo to lowercase
      id: repo
      run: echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}:${{ env.DATE }}

    - name: Test if the image serves the page
      run: |
        docker run -d -p 80:80 ghcr.io/${{ env.REPO }}:${{ env.DATE }}
        curl --max-time 10 --retry 5 http://localhost:80